nelmio_api_doc:
    documentation:
        servers:
            - url: http://billing.study-on.local:82
              description: API over HTTP
        info:
            title: Stady-on.BILLING
            description: Billing servise for study-on!
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
                    name: Authorization
        security:
            - Bearer: []
